---
- name: Create CA key
  openssl_privatekey:
    path: /etc/squid/ssl_cert/CA_key.pem
  register: ca_key

- name: create the CA CSR
  openssl_csr:
    path: /etc/squid/ssl_cert/CA.csr
    privatekey_path: "{{ ca_key.filename }}"
    common_name: "my-ca"
  register: ca_csr

- name: sign the CA CSR
  openssl_certificate:
    path: /etc/squid/ssl_cert/CA.pem
    csr_path: "{{ ca_csr.filename }}"
    privatekey_path: "{{ ca_key.filename }}"
    provider: selfsigned

- name: Merge CA + key
  shell:
    cmd: 'cat CA_key.pem CA.pem > CA_and_key.pem'
  args:
    chdir: /etc/squid/ssl_cert/
  notify: Re-start Squid