---
- name: Install Squid
  include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Setting TLS proxy
  import_tasks: https.yml
  when: (http_port['modes'] is defined) and ("ssl-bump" in http_port['modes'])

- name: Copy config file
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: '0644'
  notify: Enable and start Squid
