---
- name: Install the latest version of Squid
  dnf:
    name: squid
    state: latest
  notify: Enable and start Squid

- name: Install the latest crypto packages
  dnf:
    name: python3-pyOpenSSL
    state: latest
  when: (http_port['modes'] is defined) and ("ssl_bump" in http_port['modes'])
